### ISSUE TITLE
agent-scheduler changes global CSS to bad values

### ISSUE THREAD

**Issue by vladmandic** [ArtVentureX/sd-webui-agent-scheduler#123]
i've just noticed that some bad values in css are set by agent-scheduler. for example there are several tags such as:

```css
@media (min-width: 1280px)
.container {
    max-width: 1280px;
}
```

but `.container` is not a private class of agent-scheduler, its a GLOBAL class.
no extension should change global class - this is very bad and considered hostile!

if agent scheduler wants to have media tags, that's totally fine - just make sure its using private classes (e.g. prepent all class names uses by agent scheduler with `as-` or something like that.
